containers: cuda contianer needs libcudann8 and nvidia-driver-NVML
The libcudann8 container needs to be installed in the container or
else we see errors like this one:

    File "/usr/local/lib64/python3.11/site-packages/torch/__init__.py", line 237, in <module>
        from torch._C import *  # noqa: F403
        ^^^^^^^^^^^^^^^^^^^^^^
    ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

And in order to find devices in torch:

    $ python3.11
    >>> import torch
    >>> torch.cuda.device_count()
    1

The above returns zero without nvidia-driver-NVML

Signed-off-by: Stef Walter <stefw@redhat.com>