Don't fail if multiprocessing is already set to spawn
Python multiprocessing does not allow th change the default start method
when another code path has already configured a default start method.
Even `get_start_method` or `get_context` sets a default context.

I was running into this exception when doing training with some hardware
accelerator frameworks like Habana.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

Signed-off-by: Christian Heimes <cheimes@redhat.com>