Make threads parameter optional for serve()
* New parameter was added without a default. Not all callers were updated.
* So we are getting:
    `TypeError: server() missing 1 required positional argument: 'threads'`
* Just adding a default fixes the problem

Signed-off-by: markstur <mark.sturdevant@ibm.com>