Support GPU offloading for lab train on Linux (#520)
* GPU acceleration for lab train on Linux

`lab train` now supports NVidia CUDA and AMD ROCm devices to speed training.
GPU acceleration is enabled with `lab train --device cuda`.

The `--device` argument takes the same value as `torch.device()` API.
Values like `cuda:0` for first CUDA card work, too. Default value is
`cpu`. Other possible values are ipu, xpu, mkldnn, opengl, opencl,
ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia,
privateuseone.

GPU acceleration requires a lot of GPU memory. On AMD GPUs, memory
consumption peaks at about 17 GiB. Training on GPU has been successfully
tested on

- NVidia GeForce RTX 3090 (24 GiB), Fedora 39, PyTorch 2.2.1 CUDA 12.1
- Radeon RX 7900 XT (20 GiB), Fedora 39, PyTorch 2.2.1+rocm5.7
- Radeon RX 7900 XTX (24 GiB), Fedora 39, PyTorch 2.2.1+rocm5.7

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Add option to use 4-bit quant with BitsAndBytes

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* 4-bit quant changes

- rename option to `--4-bit-quant`
- hide option until llamaccp_convert_to_gguf supports quantized models

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Mention to stop server, RTX 20 is too old

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Add RTX 3060 on WSL2

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Add auto device map, improve code

- use Torch device from `model.device`
- use `device_map` instead of moving model to device after loading
- add support for auto device mapping (currently fails for me on ROCm,
  see #610)

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Apply documentation improvements contributed by Mark Bestavros

Co-authored-by: Mark Bestavros <markbest@bu.edu>
Signed-off-by: Christian Heimes <christian@python.org>

* More debug tips for ROCm

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Auto device map is not designed for training

Ben figured out that auto device map is only usable for interferencing.

See: https://discuss.huggingface.co/t/using-device-map-auto-for-training/46321
Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Skip bitsandbytes 4-bit quant is not working, yet

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Apply doc improvements from Kelly Brown

Co-authored-by: Kelly Brown <86735520+kelbrown20@users.noreply.github.com>
Signed-off-by: Christian Heimes <christian@python.org>

* More doc improvements

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Document experimental settings for GPU

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Allow --4-bit-quant parameter

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Report GPU device capabilities, test more dtypes

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Only allow cuda or cpu device, improve error reporting

```shell
$ lab train --device invalid
Usage: lab train [OPTIONS]
Try 'lab train --help' for help.

Error: Invalid value for '--device': Only 'cpu', 'cuda', cuda with device index ('cuda:0') are currently supported.
```

```shell
$ lab train --4-bit-quant
Usage: lab train [OPTIONS]
Try 'lab train --help' for help.

Error: --4-bit-quant option requires --device=cuda
```

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Clarify comment in requirements.txt

Signed-off-by: Christian Heimes <cheimes@redhat.com>

* Refactor Torch device parameter

The old named tuple is gone and the code now lives in `cli.lab`.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

---------

Signed-off-by: Christian Heimes <cheimes@redhat.com>
Signed-off-by: Christian Heimes <christian@python.org>
Co-authored-by: Mark Bestavros <markbest@bu.edu>
Co-authored-by: Kelly Brown <86735520+kelbrown20@users.noreply.github.com>