deps: add yq as installation dependency
There is a missing dependency on yq which cause 'ilab taxonomy diff'
command to fail with below error:

  WARNING (...)  instructlab.schema.taxonomy:336: could not run yq command
  Traceback (most recent call last):
  File "(...)/lib64/python3.11/site-packages/instructlab/schema/taxonomy.py", line 331, in _schema_validate
    line = subprocess.check_output(["yq", yq_expression], input=text, text=True)
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['yq', '.seed_examples[19].questions_and_answers | line']' returned non-zero exit status 3.

Signed-off-by: Radoslaw Smigielski <rsmigiel@redhat.com>