Fix backtrace via `lab chat` `ensure_server()` call
PR #423 missed adding a `threads` argument to the `server()` call
from `ensure_server()`. The latter is called when `lab chat` is used
before a `lab serve`:

```
$ lab chat
...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
TypeError: server() missing 1 required positional argument: 'threads'
```

Make the `threads` argument to `server()` optional. That will
probably be easier for plugging in future `threads` config file
support too

Resolves: https://github.com/instruct-lab/cli/issues/566

Signed-off-by: Cole Robinson <crobinso@redhat.com>