Fix chat context switching
Any attempt to switch context ended up with:

   File "/Users/xx/src/xxx/instructlab/src/instructlab/utils.py", line 797, in is_model_gguf
    with model_path.open("rb") as f:
         ^^^^^^^^^^^^^^^
   AttributeError: 'str' object has no attribute 'open'

Unfortunately changing the argument of get_model_arch() from string to
pathlib.Path does not fully resolve the problem because get_sysprompt()
and get_sysprompt had a different argument list, in order to unify both
I added arch string argument to get_cli_helper_sysprompt() which is
ignored but in that way both functions accept the same list of
arguments.

Fixes: #2730
Signed-off-by: Radoslaw Smigielski <rsmigiel@redhat.com>

build(deps): bump docker/build-push-action from 6.9.0 to 6.10.0

Bumps [docker/build-push-action](https://github.com/docker/build-push-action) from 6.9.0 to 6.10.0.
- [Release notes](https://github.com/docker/build-push-action/releases)
- [Commits](https://github.com/docker/build-push-action/compare/4f58ea79222b3b9dc2c8bbdd6debcef730109a75...48aba3b46d1b1fec4febb7c5d0c644b249a11355)

---
updated-dependencies:
- dependency-name: docker/build-push-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Add disk check after tests run

Signed-off-by: Dan McPherson <dmcphers@redhat.com>