ux: Handle outdated config file more gracefully
Commit 31b64f475a9ae0571e5903f776b9fbd00bc71dde dropped
`list.taxonomy_path` from the config file. This change handles the
config parsing error more gracefully.  Previously, you'd get a stack
trace that ends with something like:

```
  File "/Users/rbryant/src/instructlab/cli/cli/lab.py", line 57, in configure
    ctx.obj = Lab(filename)
  File "/Users/rbryant/src/instructlab/cli/cli/lab.py", line 40, in __init__
    self.config = config.read_config(filename)
  File "/Users/rbryant/src/instructlab/cli/cli/config.py", line 99, in read_config
    raise ConfigException(config_file) from exc
cli.config.ConfigException: Configuration file config.yaml does not exist or contains invalid YAML.

```

The new behavior is:

```
Error: Configuration file config.yaml is using an outdated format. Run `lab init` again.
```

Signed-off-by: Russell Bryant <rbryant@redhat.com>