mypy: Added missing type hint
This fixes the following error:

error: Need type annotation for "shard" (hint: "shard: dict[<type>,
<type>] = ...")  [var-annotated]

Signed-off-by: Ihar Hrachyshka <ihrachys@redhat.com>