Require setuptools >= 70.1.0 to build wheel
setuptools < 70.0 have a bug in the schema definition for dynamic
optional dependencies. The issue was fixed in validate-pyproject 0.17
and setuptools 70.0.0.

70.1.0 has another fix that might be relevant for Python 3.10.

This fixes the following error message:

```
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}
```

See: https://github.com/abravalheri/validate-pyproject/pull/170
Signed-off-by: Christian Heimes <cheimes@redhat.com>