ci: Force use of constraints file for all `pip install` commands
Otherwise, pip may install a version of a package that does not satisfy
the constraints; then fail to honour the constraints because:

```
ERROR: pip's dependency resolver does not currently take into account
all the packages that are installed. This behaviour is the source of the
following dependency conflicts.
```

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
(cherry picked from commit e89b6fb8822a7ad4ba62a05de523dbf2986798f5)