Fix chat context switching
Any attempt to switch context ended up with:

   File "/Users/xx/src/xxx/instructlab/src/instructlab/utils.py", line 797, in is_model_gguf
    with model_path.open("rb") as f:
         ^^^^^^^^^^^^^^^
   AttributeError: 'str' object has no attribute 'open'

Unfortunately changing the argument of get_model_arch() from string to
pathlib.Path does not fully resolve the problem because get_sysprompt()
and get_sysprompt had a different argument list, in order to unify both
I added arch string argument to get_cli_helper_sysprompt() which is
ignored but in that way both functions accept the same list of
arguments.

Fixes: #2730
Signed-off-by: Radoslaw Smigielski <rsmigiel@redhat.com>