Update requirements.txt
Try updating dependency to allow installation within rhoai notebook.  Error is:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.18.1 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.38 which is incompatible.

Signed-off-by: David Williams <dww@pacificera.com>